sudo: required
services:
  - docker

before_install:
  - docker build -t apazga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run apazga/react-test npm test -- --coverage

after_success:
  - docker build -t apazga/react-multi-client ./client
  - docker build -t apazga/react-multi-nginx ./nginx
  - docker build -t apazga/react-multi-server ./server
  - docker build -t apazga/react-multi-worker ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push apazga/react-multi-client
  - docker push apazga/react-multi-nginx
  - docker push apazga/react-multi-server
  - docker push apazga/react-multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: react-multi-docker
  env: ReactMultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-159664229896
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY